name: gh-pages

on:
  push:
    branches:
      # - main
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.12.0
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: ${{ runner.os }}-opam-${{ hashFiles('**/*.opam') }}
          restore-keys: ${{ runner.os }}-opam-
      - run: opam install . --deps-only --with-test
      - run: opam install odoc
      - run: opam exec -- dune build @doc
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/_doc/_html
